# Generated by Django 3.0 on 2020-01-02 14:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191231_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='update_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
    ]
