# Generated by Django 3.0.4 on 2020-04-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
    ]
